// Generated by gencpp from file simple_filter/LaserSimple.msg
// DO NOT EDIT!


#ifndef SIMPLE_FILTER_MESSAGE_LASERSIMPLE_H
#define SIMPLE_FILTER_MESSAGE_LASERSIMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_filter
{
template <class ContainerAllocator>
struct LaserSimple_
{
  typedef LaserSimple_<ContainerAllocator> Type;

  LaserSimple_()
    : north_laser(0.0)
    , south_laser(0.0)
    , east_laser(0.0)
    , west_laser(0.0)  {
    }
  LaserSimple_(const ContainerAllocator& _alloc)
    : north_laser(0.0)
    , south_laser(0.0)
    , east_laser(0.0)
    , west_laser(0.0)  {
  (void)_alloc;
    }



   typedef double _north_laser_type;
  _north_laser_type north_laser;

   typedef double _south_laser_type;
  _south_laser_type south_laser;

   typedef double _east_laser_type;
  _east_laser_type east_laser;

   typedef double _west_laser_type;
  _west_laser_type west_laser;




  typedef boost::shared_ptr< ::simple_filter::LaserSimple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_filter::LaserSimple_<ContainerAllocator> const> ConstPtr;

}; // struct LaserSimple_

typedef ::simple_filter::LaserSimple_<std::allocator<void> > LaserSimple;

typedef boost::shared_ptr< ::simple_filter::LaserSimple > LaserSimplePtr;
typedef boost::shared_ptr< ::simple_filter::LaserSimple const> LaserSimpleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_filter::LaserSimple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_filter::LaserSimple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_filter': ['/home/borg/catkin_ws/src/robot17/particle_filter/simple_filter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_filter::LaserSimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_filter::LaserSimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_filter::LaserSimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_filter::LaserSimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_filter::LaserSimple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_filter::LaserSimple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_filter::LaserSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8187ec0e932eb25ced46dca14c4680";
  }

  static const char* value(const ::simple_filter::LaserSimple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8187ec0e932eb2ULL;
  static const uint64_t static_value2 = 0x5ced46dca14c4680ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_filter::LaserSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_filter/LaserSimple";
  }

  static const char* value(const ::simple_filter::LaserSimple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_filter::LaserSimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 north_laser\n\
float64 south_laser\n\
float64 east_laser\n\
float64 west_laser\n\
";
  }

  static const char* value(const ::simple_filter::LaserSimple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_filter::LaserSimple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.north_laser);
      stream.next(m.south_laser);
      stream.next(m.east_laser);
      stream.next(m.west_laser);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaserSimple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_filter::LaserSimple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_filter::LaserSimple_<ContainerAllocator>& v)
  {
    s << indent << "north_laser: ";
    Printer<double>::stream(s, indent + "  ", v.north_laser);
    s << indent << "south_laser: ";
    Printer<double>::stream(s, indent + "  ", v.south_laser);
    s << indent << "east_laser: ";
    Printer<double>::stream(s, indent + "  ", v.east_laser);
    s << indent << "west_laser: ";
    Printer<double>::stream(s, indent + "  ", v.west_laser);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_FILTER_MESSAGE_LASERSIMPLE_H
