// Generated by gencpp from file simple_filter/VelocitySimple.msg
// DO NOT EDIT!


#ifndef SIMPLE_FILTER_MESSAGE_VELOCITYSIMPLE_H
#define SIMPLE_FILTER_MESSAGE_VELOCITYSIMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_filter
{
template <class ContainerAllocator>
struct VelocitySimple_
{
  typedef VelocitySimple_<ContainerAllocator> Type;

  VelocitySimple_()
    : west_to_east_velocity(0.0)
    , south_to_north_velocity(0.0)  {
    }
  VelocitySimple_(const ContainerAllocator& _alloc)
    : west_to_east_velocity(0.0)
    , south_to_north_velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _west_to_east_velocity_type;
  _west_to_east_velocity_type west_to_east_velocity;

   typedef double _south_to_north_velocity_type;
  _south_to_north_velocity_type south_to_north_velocity;




  typedef boost::shared_ptr< ::simple_filter::VelocitySimple_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_filter::VelocitySimple_<ContainerAllocator> const> ConstPtr;

}; // struct VelocitySimple_

typedef ::simple_filter::VelocitySimple_<std::allocator<void> > VelocitySimple;

typedef boost::shared_ptr< ::simple_filter::VelocitySimple > VelocitySimplePtr;
typedef boost::shared_ptr< ::simple_filter::VelocitySimple const> VelocitySimpleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_filter::VelocitySimple_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_filter::VelocitySimple_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'simple_filter': ['/home/borg/catkin_ws/src/robot17/particle_filter/simple_filter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_filter::VelocitySimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_filter::VelocitySimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_filter::VelocitySimple_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_filter::VelocitySimple_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_filter::VelocitySimple_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_filter::VelocitySimple_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_filter::VelocitySimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d1fc69ecbb9c4cf4162781c2abe97c";
  }

  static const char* value(const ::simple_filter::VelocitySimple_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d1fc69ecbb9c4cULL;
  static const uint64_t static_value2 = 0xf4162781c2abe97cULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_filter::VelocitySimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_filter/VelocitySimple";
  }

  static const char* value(const ::simple_filter::VelocitySimple_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_filter::VelocitySimple_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 west_to_east_velocity\n\
float64 south_to_north_velocity\n\
";
  }

  static const char* value(const ::simple_filter::VelocitySimple_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_filter::VelocitySimple_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.west_to_east_velocity);
      stream.next(m.south_to_north_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocitySimple_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_filter::VelocitySimple_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_filter::VelocitySimple_<ContainerAllocator>& v)
  {
    s << indent << "west_to_east_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.west_to_east_velocity);
    s << indent << "south_to_north_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.south_to_north_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_FILTER_MESSAGE_VELOCITYSIMPLE_H
