// Generated by gencpp from file neato_node/Bump.msg
// DO NOT EDIT!


#ifndef NEATO_NODE_MESSAGE_BUMP_H
#define NEATO_NODE_MESSAGE_BUMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neato_node
{
template <class ContainerAllocator>
struct Bump_
{
  typedef Bump_<ContainerAllocator> Type;

  Bump_()
    : leftFront(0)
    , leftSide(0)
    , rightFront(0)
    , rightSide(0)  {
    }
  Bump_(const ContainerAllocator& _alloc)
    : leftFront(0)
    , leftSide(0)
    , rightFront(0)
    , rightSide(0)  {
  (void)_alloc;
    }



   typedef uint8_t _leftFront_type;
  _leftFront_type leftFront;

   typedef uint8_t _leftSide_type;
  _leftSide_type leftSide;

   typedef uint8_t _rightFront_type;
  _rightFront_type rightFront;

   typedef uint8_t _rightSide_type;
  _rightSide_type rightSide;




  typedef boost::shared_ptr< ::neato_node::Bump_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_node::Bump_<ContainerAllocator> const> ConstPtr;

}; // struct Bump_

typedef ::neato_node::Bump_<std::allocator<void> > Bump;

typedef boost::shared_ptr< ::neato_node::Bump > BumpPtr;
typedef boost::shared_ptr< ::neato_node::Bump const> BumpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neato_node::Bump_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neato_node::Bump_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neato_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'neato_node': ['/home/borg/catkin_ws/src/robot17/neato_robot/neato_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neato_node::Bump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neato_node::Bump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neato_node::Bump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neato_node::Bump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neato_node::Bump_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neato_node::Bump_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neato_node::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "459d87767ce0f2ebdc162046e9ad2c13";
  }

  static const char* value(const ::neato_node::Bump_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x459d87767ce0f2ebULL;
  static const uint64_t static_value2 = 0xdc162046e9ad2c13ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_node::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neato_node/Bump";
  }

  static const char* value(const ::neato_node::Bump_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neato_node::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents the bump sensor data from the Neato \n\
\n\
uint8 leftFront\n\
uint8 leftSide\n\
uint8 rightFront\n\
uint8 rightSide \n\
";
  }

  static const char* value(const ::neato_node::Bump_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neato_node::Bump_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftFront);
      stream.next(m.leftSide);
      stream.next(m.rightFront);
      stream.next(m.rightSide);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bump_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neato_node::Bump_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neato_node::Bump_<ContainerAllocator>& v)
  {
    s << indent << "leftFront: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leftFront);
    s << indent << "leftSide: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leftSide);
    s << indent << "rightFront: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rightFront);
    s << indent << "rightSide: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rightSide);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEATO_NODE_MESSAGE_BUMP_H
